In [1]:
pip install numpy


In [1]:
import numpy as np

In [2]:
myarr=np.array([1,2,3,4])

In [3]:
myarr

array([1, 2, 3, 4])

In [4]:
myarr[2]

3

In [5]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listarray.dtype

dtype('int64')

In [8]:
listarray.shape

(3, 3)

In [9]:
zeros=np.zeros((2,4))

In [10]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
rng=np.arange(15)

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace=np.linspace(1,10,7)

In [14]:
lspace

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [15]:
ide = np.identity(5)

In [16]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
arr=np.arange(99)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [19]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
arr=arr.reshape(3,33)

In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [23]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [25]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [26]:
ar.sum(axis=0)

array([12,  8,  9])

In [27]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [28]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [29]:
ar.flat

In [30]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [32]:
one=np.array([1,9,2,6,234,0])

In [33]:
one.argmax()

4

In [34]:
one.argmin()

5

In [35]:
one.argsort()

array([5, 0, 2, 3, 1, 4])

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar.argmin()

8

In [38]:
ar.argmax()

6

In [39]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [40]:
ar.argmax(axis=0)

array([2, 1, 1])

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar2=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [45]:
ar+ar2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 10, 10]])

In [46]:
ar*ar2

array([[ 2,  6, 12],
       [20, 30, 42],
       [56,  9,  0]])

In [47]:
ar.sum()

29

In [48]:
ar.max()

7

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))